package model.views.client;

import model.views.common.XxOmBpoInfoTVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 07 11:55:22 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxOmBpoInfoTVOClient extends ViewUsageImpl implements XxOmBpoInfoTVO {
    /**
     * This is the default constructor (do not remove).
     */
    public XxOmBpoInfoTVOClient() {
    }

    public void getpocid(String PocId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getpocid",new String [] {"java.lang.String"},new Object[] {PocId});
        return;
    }
}
