package model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 07 11:55:21 BDT 2021
// ---------------------------------------------------------------------
public interface XxOmBpoInfoTVO extends ViewObject {
    void getpocid(String PocId);
}
