package model.views;

import model.views.common.XxOmBpoInfoTVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 07 11:54:04 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxOmBpoInfoTVOImpl extends ViewObjectImpl implements XxOmBpoInfoTVO {
    /**
     * This is the default constructor (do not remove).
     */
    public XxOmBpoInfoTVOImpl() {
    }

    /**
     * Returns the bind variable value for param.
     * @return bind variable value for param
     */
    public String getparam() {
        return (String)getNamedWhereClauseParam("param");
    }

    /**
     * Sets <code>value</code> for bind variable param.
     * @param value value to bind as param
     */
    public void setparam(String value) {
        setNamedWhereClauseParam("param", value);
    }
    public void getpocid(String PocId) {
       System.out.println(PocId);
    }
    
}
