package model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 24 09:24:17 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Country_LovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Country_LovImpl() {
    }


    /**
     * Returns the variable value for buyerid.
     * @return variable value for buyerid
     */
    public String getbuyerid() {
        return (String)ensureVariableManager().getVariableValue("buyerid");
    }

    /**
     * Sets <code>value</code> for variable buyerid.
     * @param value value to bind as buyerid
     */
    public void setbuyerid(String value) {
        ensureVariableManager().setVariableValue("buyerid", value);
    }
}
