package model.services;

import java.awt.event.ActionEvent;


import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import model.lov.Country_LovImpl;

import model.services.common.AppModule;

import model.views.XxOmBpoInfoTVOImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 12 16:50:59 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for XxOmBpoInfoTVO1.
     * @return XxOmBpoInfoTVO1
     */
    public ViewObjectImpl getXxOmBpoInfoTVO1() {
        return (ViewObjectImpl)findViewObject("XxOmBpoInfoTVO1");
    }

    /**
     * Container's getter for XxOmPocLTVO1.
     * @return XxOmPocLTVO1
     */
    public ViewObjectImpl getXxOmPocLTVO1() {
        return (ViewObjectImpl)findViewObject("XxOmPocLTVO1");
    }

    /**
     * Container's getter for FOBLOV1.
     * @return FOBLOV1
     */
    public ViewObjectImpl getFOBLOV1() {
        return (ViewObjectImpl)findViewObject("FOBLOV1");
    }


    /**
     * Container's getter for SumOfView_bpo_info_t1.
     * @return SumOfView_bpo_info_t1
     */
    public ViewObjectImpl getSumOfView_bpo_info_t1() {
        return (ViewObjectImpl)findViewObject("SumOfView_bpo_info_t1");
    }

    /**
     * Container's getter for Country_Lov1.
     * @return Country_Lov1
     */
    public ViewObjectImpl getCountry_Lov1() {
        return (ViewObjectImpl)findViewObject("Country_Lov1");
    }

    /**
     * Container's getter for XxOmSizewiseLTVO1.
     * @return XxOmSizewiseLTVO1
     */
    public ViewObjectImpl getXxOmSizewiseLTVO1() {
        return (ViewObjectImpl)findViewObject("XxOmSizewiseLTVO1");
    }

    /**
     * Container's getter for XxOmSizewiseLTVO2.
     * @return XxOmSizewiseLTVO2
     */
    public ViewObjectImpl getXxOmSizewiseLTVO2() {
        return (ViewObjectImpl)findViewObject("XxOmSizewiseLTVO2");
    }

    /**
     * Container's getter for sizewiseLtViabpoInfoTVL1.
     * @return sizewiseLtViabpoInfoTVL1
     */
    public ViewLinkImpl getsizewiseLtViabpoInfoTVL1() {
        return (ViewLinkImpl)findViewLink("sizewiseLtViabpoInfoTVL1");
    }

    /**
     * Container's getter for poc_searchVO1.
     * @return poc_searchVO1
     */
    public ViewObjectImpl getpoc_searchVO1() {
        return (ViewObjectImpl)findViewObject("poc_searchVO1");
    }
    
    public void setSessionValues( String userId) {

            System.out.println("UserId....." + userId);
            //System.out.println("OrgID..." + orgId);

            


            if (userId != null) {
                FacesContext fctx = FacesContext.getCurrentInstance();
                ExternalContext ectx = fctx.getExternalContext();
                HttpSession userSession = (HttpSession)ectx.getSession(false);
                userSession.setAttribute("userId", userId);
                 
                System.out.println("User name is :"+userId);
        
            }
        }


}
